import { defineSemanticTokens } from '@chakra-ui/react';

import {
  buttonSemanticTokens,
  tabsSemanticTokens,
  inputSemanticTokens,
  cardSemanticTokens,
  headingSemanticTokens,
  checkboxSemanticTokens,
  textSemanticTokens,
  linkSemanticTokens,
  sectionSemanticTokens,
  navbarSemanticTokens,
  iconSemanticTokens,
  radioSemanticTokens,
  selectSemanticTokens,
  textareaSemanticTokens,
  badgeSemanticTokens,
} from './components';

export const semanticTokens = defineSemanticTokens({
  colors: {
    bg: {
      button: buttonSemanticTokens.bg,
      tabs: tabsSemanticTokens.bg,
      input: inputSemanticTokens.bg,
      card: cardSemanticTokens.bg,
      checkbox: checkboxSemanticTokens.bg,
      section: sectionSemanticTokens.bg,
      navbar: navbarSemanticTokens.bg,
      radio: radioSemanticTokens.bg,
      select: selectSemanticTokens.bg,
      textarea: textareaSemanticTokens.bg,
      badge: badgeSemanticTokens.bg,
    },
    icon: iconSemanticTokens.color,
    text: {
      ...textSemanticTokens.text,
      button: buttonSemanticTokens.text,
      tabs: tabsSemanticTokens.text,
      input: inputSemanticTokens.text,
      heading: headingSemanticTokens.text,
      card: cardSemanticTokens.text,
      radio: radioSemanticTokens.text,
      select: selectSemanticTokens.text,
      link: linkSemanticTokens.text,
      textarea: textareaSemanticTokens.text,
      badge: badgeSemanticTokens.text,
    },
    border: {
      tabs: tabsSemanticTokens.border,
      input: inputSemanticTokens.border,
      card: cardSemanticTokens.border,
      checkbox: checkboxSemanticTokens.border,
      section: sectionSemanticTokens.border,
      navbar: navbarSemanticTokens.border,
      radio: radioSemanticTokens.border,
      select: selectSemanticTokens.border,
      textarea: textareaSemanticTokens.border,
      badge: badgeSemanticTokens.border,
    },
  },
  fontSizes: {
    button: buttonSemanticTokens.fontSizes,
    tabs: tabsSemanticTokens.fontSizes,
    input: inputSemanticTokens.fontSizes,
    heading: headingSemanticTokens.fontSizes,
    text: textSemanticTokens.fontSizes,
    link: linkSemanticTokens.fontSizes,
    select: selectSemanticTokens.fontSizes,
    radio: radioSemanticTokens.fontSizes,
    textarea: textareaSemanticTokens.fontSizes,
  },
  fontWeights: {
    tabs: tabsSemanticTokens.fontWeights,
    input: inputSemanticTokens.fontWeights,
    button: buttonSemanticTokens.fontWeights,
    heading: headingSemanticTokens.fontWeights,
    text: textSemanticTokens.fontWeights,
    link: linkSemanticTokens.fontWeights,
    select: selectSemanticTokens.fontWeights,
    radio: radioSemanticTokens.fontWeights,
    textarea: textareaSemanticTokens.fontWeights,
  },
  radii: {
    button: buttonSemanticTokens.radii,
    tabs: tabsSemanticTokens.radii,
    input: inputSemanticTokens.radii,
    checkbox: checkboxSemanticTokens.radii,
    section: sectionSemanticTokens.radii,
    navbar: navbarSemanticTokens.radii,
    select: selectSemanticTokens.radii,
    card: cardSemanticTokens.radii,
    badge: badgeSemanticTokens.radii,
  },
});
